# setup docker for couchdb
- hosts: couchdbnodes
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: couchdb-docker

# setup cluster
- hosts: masternode
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: couchdb-cluster