- hosts: nodes
  vars_files:
    - host_vars/mountpoint.yaml
  gather_facts: false
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ccc_a2.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: common
    - role: volumes
    - role: docker

# setup docker for couchdb
- hosts: couchdbnodes
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: couchdb-docker

# setup cluster
- hosts: masternode
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: couchdb-cluster

- hosts: web
  vars_files:
    - host_vars/git.yaml
    - host_vars/user.yaml
  gather_facts: true

  roles:
    - role: git-clone

- hosts: crawler
  vars_files:
    - host_vars/git.yaml
    - host_vars/user.yaml
  gather_facts: true

  roles:
    - role: git-clone

- hosts: crawler
  vars_files:
    - host_vars/git.yaml
  gather_facts: true
  roles:
    - role: crawler

- hosts: web
  vars_files:
    - host_vars/git.yaml
  gather_facts: true
  roles:
    - role: web-build


