- hosts: nodes
  vars_files:
    - host_vars/mountpoint.yaml
  gather_facts: false
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ccc_a2.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: common
    - role: volumes
    - role: docker