# Common vars 
availability_zone: melbourne-qh2-uom # timezone - dont change
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999 # NeCTAR Ubuntu - dont change
instance_key_name: ccc_a2 # generated keypair
instance_flavor: uom.mse.2c9g # for each instance, 8 cores limited
instance_network: qh2-uom-internal # network type - dont change

# Volume
# except firstnode, couchdb are setup
volumes:
  - vol_name: node-01-vol-docker # less mem since no heavy work 
    vol_size: 10
  - vol_name: node-01-vol-data
    vol_size: 10
  - vol_name: node-02-vol-docker # couchdb and crawler
    vol_size: 10
  - vol_name: node-02-vol-data
    vol_size: 50
  - vol_name: node-03-vol-docker
    vol_size: 10
  - vol_name: node-03-vol-data
    vol_size: 50
  - vol_name: node-04-vol-docker
    vol_size: 10
  - vol_name: node-04-vol-data
    vol_size: 50
  

# Security group - maybe change later
security_groups:
  - name: my_ssh
    description: "my security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: my_http
    description: "my security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: my_frontend
    description: "my security group for frontend"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0
  - name: my_backend
    description: "my security group for backend"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0
  - name: my_couchdb1
    description: "couchdb communication channel"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: my_couchdb2
    description: "couchdb communication channel"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: my_couchdb3
    description: "couchdb communication channel"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0


# Instance - same as the example
instances:
  - name: node1
    volumes: ['node-01-vol-docker', 'node-01-vol-data']
  - name: node2
    volumes: ['node-02-vol-docker', 'node-02-vol-data']
  - name: node3
    volumes: ['node-03-vol-docker', 'node-03-vol-data']
  - name: node4
    volumes: ['node-04-vol-docker', 'node-04-vol-data']


