# adapted from https://gitlab.unimelb.edu.au/feit-comp90024/comp90024/-/tree/master/couchdb

---
- name: Setup Slave Nodes as cluster of Master Node
  become: yes
  uri:
    url: "http://{{ couchdb_user }}:{{ couchdb_pwd }}@{{ groups['masternode'][0] }}:{{ couchdb_port }}/_cluster_setup"
    method: POST
    force_basic_auth: yes # allow user autentication
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
             \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_pwd }}\", \"port\": \"{{ couchdb_port }}\",\
             \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ groups['couchdbnodes'] | length }}\",\
             \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":\"{{ couchdb_pwd }}\"}"
    status_code: 201 # 201 for successfull setup, 400 for bad request(usually cluster is already enabled)
  loop: "{{ groups['slavenode'] }}"

- name: add Slave Nodes to Master Node
  become: yes
  uri:
    url: "http://{{ couchdb_user }}:{{ couchdb_pwd }}@{{ groups['masternode'][0] }}:{{ couchdb_port }}/_cluster_setup"
    method: POST
    force_basic_auth: yes # allow user autentication
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\": \"add_node\", \"host\":\"{{ item }}\",\
             \"port\": \"{{ couchdb_port }}\", \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_pwd }}\"}"
    status_code: 201 # 201 for successfull setup, 400 for bad request(usually cluster is already enabled)
  loop: "{{ groups['slavenode'] }}"

- name: finish cluster setup
  become: yes
  uri:
    url: "http://{{ couchdb_user }}:{{ couchdb_pwd }}@{{ groups['masternode'][0] }}:{{ couchdb_port }}/_cluster_setup"
    method: POST
    force_basic_auth: yes # allow user autentication
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\": \"finish_cluster\"}"
    status_code: 201,500 # 201 for successfull setup. Ignore the {"error":"setup_error","reason":"Cluster setup unable to sync admin passwords"} message.