---
- name: config docker-compose
  become: True
  shell:
    cmd: "sudo chmod 666 /var/run/docker.sock"
    chdir: /
- name: run web docker compose
  docker_compose:
    project_src: "{{ web_dest_path }}"